import type { Mission } from '@/missions/types/mission.types'

export const MISSION_CATALOG: Mission[] = [
  {
    id: 'math-rhythmic-counting',
    type: 'rhythmic-counting',
    subject: 'math',
    title: 'Sayı Treni',
    description: "2'şer, 3'er, 5'er, 10'ar ritmik say!",
    icon: '🚂',
    difficulty: 1,
    rewardStars: 10,
    estimatedMinutes: 8,
    completionCriteria: { minQuestions: 5, minAccuracy: 0.6 },
  },
  {
    id: 'math-addition',
    type: 'addition',
    subject: 'math',
    title: 'Toplama Macerası',
    description: "100'e kadar toplama!",
    icon: '➕',
    difficulty: 1,
    rewardStars: 10,
    estimatedMinutes: 7,
    completionCriteria: { minQuestions: 5, minAccuracy: 0.6 },
  },
  {
    id: 'math-subtraction',
    type: 'subtraction',
    subject: 'math',
    title: 'Çıkarma Oyunu',
    description: "100'e kadar çıkarma!",
    icon: '➖',
    difficulty: 1,
    rewardStars: 10,
    estimatedMinutes: 7,
    completionCriteria: { minQuestions: 5, minAccuracy: 0.6 },
  },
  {
    id: 'math-multiplication',
    type: 'multiplication',
    subject: 'math',
    title: 'Çarpım Tablosu',
    description: '2 ve 3 ile çarp!',
    icon: '✖️',
    difficulty: 1,
    rewardStars: 15,
    estimatedMinutes: 10,
    completionCriteria: { minQuestions: 5, minAccuracy: 0.6 },
  },
  {
    id: 'math-shapes',
    type: 'shapes',
    subject: 'math',
    title: 'Şekil Macerası',
    description: 'Köşe, kenar ve şekil adları!',
    icon: '🔷',
    difficulty: 1,
    rewardStars: 10,
    estimatedMinutes: 7,
    completionCriteria: { minQuestions: 5, minAccuracy: 0.6 },
  },
  {
    id: 'math-missing-number',
    type: 'missing-number',
    subject: 'math',
    title: 'Boşluğu Bul',
    description: 'Eksik sayıyı tahmin et!',
    icon: '❓',
    difficulty: 1,
    rewardStars: 12,
    estimatedMinutes: 8,
    completionCriteria: { minQuestions: 5, minAccuracy: 0.6 },
  },
  {
    id: 'logic-odd-one-out',
    type: 'odd-one-out',
    subject: 'logic',
    title: 'Hangisi Farklı?',
    description: 'Gruba uymayanı seç!',
    icon: '🔍',
    difficulty: 1,
    rewardStars: 10,
    estimatedMinutes: 7,
    completionCriteria: { minQuestions: 5, minAccuracy: 0.6 },
  },
  {
    id: 'logic-riddles',
    type: 'riddles',
    subject: 'logic',
    title: 'Bilmece Avı',
    description: 'Bilmeceleri çöz!',
    icon: '🧠',
    difficulty: 1,
    rewardStars: 12,
    estimatedMinutes: 8,
    completionCriteria: { minQuestions: 5, minAccuracy: 0.6 },
  },
  {
    id: 'logic-true-false',
    type: 'true-false',
    subject: 'logic',
    title: 'Doğru mu Yanlış mı?',
    description: 'Gerçeği ve hayali ayır!',
    icon: '🤔',
    difficulty: 1,
    rewardStars: 10,
    estimatedMinutes: 7,
    completionCriteria: { minQuestions: 5, minAccuracy: 0.6 },
  },
  {
    id: 'logic-story-order',
    type: 'story-order',
    subject: 'logic',
    title: 'Hikâye Sırası',
    description: 'Olayları doğru sıraya koy!',
    icon: '📖',
    difficulty: 1,
    rewardStars: 12,
    estimatedMinutes: 8,
    completionCriteria: { minQuestions: 5, minAccuracy: 0.6 },
  },
  {
    id: 'logic-sequence-memory',
    type: 'sequence-memory',
    subject: 'logic',
    title: 'Hafıza Zinciri',
    description: 'Diziyi izle ve hatırla!',
    icon: '🧩',
    difficulty: 1,
    rewardStars: 12,
    estimatedMinutes: 8,
    completionCriteria: { minQuestions: 5, minAccuracy: 0.6 },
  },
  {
    id: 'logic-sudoku',
    type: 'sudoku',
    subject: 'logic',
    title: 'Renkli Sudoku',
    description: '4×4 sudoku — satır ve kare kuralı!',
    icon: '🎨',
    difficulty: 1,
    rewardStars: 15,
    estimatedMinutes: 10,
    completionCriteria: { minQuestions: 5, minAccuracy: 0.6 },
  },
  {
    id: 'logic-number-sudoku',
    type: 'number-sudoku',
    subject: 'logic',
    title: 'Sayılı Sudoku',
    description: '6×6 sudoku — 1’den 6’ya, satır ve kare kuralı!',
    icon: '🔢',
    difficulty: 2,
    rewardStars: 18,
    estimatedMinutes: 12,
    completionCriteria: { minQuestions: 5, minAccuracy: 0.6 },
  },
  {
    id: 'turkish-opposites',
    type: 'opposites',
    subject: 'turkish',
    title: 'Zıt Anlamlılar',
    description: 'Zıt kelimeleri eşleştir!',
    icon: '🔄',
    difficulty: 1,
    rewardStars: 10,
    estimatedMinutes: 8,
    completionCriteria: { minQuestions: 5, minAccuracy: 0.6 },
  },
  {
    id: 'turkish-synonyms-homophones',
    type: 'synonyms-homophones',
    subject: 'turkish',
    title: 'Eş Anlamlı ve Eş Sesli',
    description: 'Eş anlamlı ve eş sesli kelimeleri eşleştir!',
    icon: '🤝',
    difficulty: 1,
    rewardStars: 10,
    estimatedMinutes: 8,
    completionCriteria: { minQuestions: 5, minAccuracy: 0.6 },
  },
  {
    id: 'turkish-syllables',
    type: 'syllables',
    subject: 'turkish',
    title: 'Heceler',
    description: 'Doğru heceyi bul!',
    icon: '📖',
    difficulty: 1,
    rewardStars: 10,
    estimatedMinutes: 8,
    completionCriteria: { minQuestions: 5, minAccuracy: 0.6 },
  },
  {
    id: 'turkish-rhyme',
    type: 'rhyme',
    subject: 'turkish',
    title: 'Kafiye Avı',
    description: 'Kafiyeli kelimeleri bul!',
    icon: '🎵',
    difficulty: 1,
    rewardStars: 10,
    estimatedMinutes: 7,
    completionCriteria: { minQuestions: 5, minAccuracy: 0.6 },
  },
  {
    id: 'life-healthy-food',
    type: 'healthy-food',
    subject: 'life',
    title: 'Sağlıklı Beslenme',
    description: 'Sağlıklı yiyecekleri seç!',
    icon: '🍎',
    difficulty: 1,
    rewardStars: 10,
    estimatedMinutes: 7,
    completionCriteria: { minQuestions: 5, minAccuracy: 0.6 },
  },
  {
    id: 'life-seasons',
    type: 'seasons',
    subject: 'life',
    title: 'Mevsimler',
    description: 'Mevsimleri sırala!',
    icon: '🌸',
    difficulty: 1,
    rewardStars: 10,
    estimatedMinutes: 7,
    completionCriteria: { minQuestions: 5, minAccuracy: 0.6 },
  },
  {
    id: 'life-days',
    type: 'days',
    subject: 'life',
    title: 'Haftanın Günleri',
    description: 'Günleri sıraya koy!',
    icon: '📅',
    difficulty: 1,
    rewardStars: 10,
    estimatedMinutes: 7,
    completionCriteria: { minQuestions: 5, minAccuracy: 0.6 },
  },
  {
    id: 'life-calendar-time',
    type: 'calendar-time',
    subject: 'life',
    title: 'Zaman ve Takvim',
    description: 'Mevsim, ay, gün ve saat bilgisi!',
    icon: '⏰',
    difficulty: 1,
    rewardStars: 10,
    estimatedMinutes: 8,
    completionCriteria: { minQuestions: 5, minAccuracy: 0.6 },
  },
  {
    id: 'logic-algorithm',
    type: 'algorithm',
    subject: 'logic',
    title: 'Dinozorun Yolunu Bul',
    description: 'Komutlarla yolu bul!',
    icon: '🦕',
    difficulty: 1,
    rewardStars: 15,
    estimatedMinutes: 10,
    completionCriteria: { minQuestions: 3, minAccuracy: 0.6 },
  },
  {
    id: 'logic-patterns',
    type: 'patterns',
    subject: 'logic',
    title: 'Örüntü Bulmaca',
    description: 'Deseni tamamla!',
    icon: '🧩',
    difficulty: 1,
    rewardStars: 10,
    estimatedMinutes: 8,
    completionCriteria: { minQuestions: 5, minAccuracy: 0.6 },
  },
]

export function getMissionById(id: string): Mission | undefined {
  return MISSION_CATALOG.find((m) => m.id === id)
}
